### ISSUE TITLE
Visual Bug in the game history after finishing a game

### ISSUE THREAD

**Issue by HeyHoHeiko** [TheSunCat/Sudoku#12]
After successfully solving a sudoko in the SAME amount of time as a previously solved sudoku, the earliest game with this time gets highlighted instead of the current one. See screenshot

![Screenshot_20230113-172323__01](https://user-images.githubusercontent.com/42236269/212371544-1e241cb1-d3f6-447d-ba4a-f0ab0f4e9b04.jpg)

**Comment by AstralShadow** [comment]
Currently the game highlights the first result with matching time.
One possible solution is passing the current game date to makeLeaderboard as well as the time.

I want to propose that instead of passing more data to makeLeaderboard, the leaderboard to be sorted with date as second sort condition - to have more recent highscores be over older highscores with same time.
This way a player gets a bit higher chance to make a leaderboard entry.
(Consider a scenario where the player has very similar scoreeboard times after playing a lot.)

**Comment by AstralShadow** [comment]
I'm proposing a fix in #13

**Comment by TheSunCat** [comment]
Should be fixed by AstralShadow's PR. I'll close it as it appears fixed in testing, but feel free to reopen if this issue reoccurs.
